# Generated by Django 2.0 on 2017-12-21 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20160704_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Project'),
        ),
    ]
